# Generated by Django 5.2 on 2025-04-21 23:41

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('access', models.CharField(choices=[('any', 'anyone'), ('email', 'email_required')], default='email', max_length=5)),
                ('status', models.CharField(choices=[('publish', 'published'), ('soon', 'coming soon'), ('draft', 'Draft')], default='draft', max_length=7)),
            ],
        ),
    ]
