# Generated by Django 5.2 on 2025-04-24 19:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_coursemodel_image_lessonmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonmodel',
            options={'ordering': ['ordering', '-datetime_updated']},
        ),
        migrations.AddField(
            model_name='lessonmodel',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonmodel',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lessonmodel',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
    ]
