# Generated by Django 5.2 on 2025-04-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_lessonmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='public_id',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
    ]
