# Generated by Django 5.2 on 2025-04-29 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_lessonmodel_public_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonmodel',
            old_name='image',
            new_name='thumbnail',
        ),
    ]
