# Generated by Django 5.2 on 2025-05-02 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_rename_image_lessonmodel_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonmodel',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_set', to='course.coursemodel'),
        ),
    ]
