# Generated by Django 5.2 on 2025-05-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_lessonmodel_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonmodel',
            name='access',
            field=models.CharField(choices=[('any', 'anyone'), ('email', 'email_required')], default='email', max_length=5),
        ),
    ]
