# Generated by Django 5.2 on 2025-05-14 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_coursesubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='course.coursesubject'),
            preserve_default=False,
        ),
    ]
