# Generated by Django 5.2 on 2025-05-21 00:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_coursemodel_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesubject',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
